# Generated by Django 3.2.8 on 2022-02-07 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=50, verbose_name='familiyasi')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.maincart', verbose_name='carts')),
            ],
        ),
    ]
