# Generated by Django 3.2.8 on 2022-02-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.PositiveIntegerField(default=1, verbose_name='phone'),
            preserve_default=False,
        ),
    ]
