# Generated by Django 4.0.2 on 2022-02-21 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=datetime.datetime(2022, 2, 21, 14, 55, 21, 550965, tzinfo=utc), max_length=200, verbose_name='Rangi'),
            preserve_default=False,
        ),
    ]
